# The minimum number of players needed before game is started
MinimumPlayers: 2

# The reward for losing
BaseReward: 50

# The reward for winning (not including wagers)
WinnerReward: 150

# Countdown amount (countdowns are done every 10 server ticks)
CountdownInSeconds: 5

# Arena's world
WorldName: world

# Range to broadcast booster messages.
BoosterBroadcastRange: 100

# Delays in milliseconds between item uses
ItemUseDelays:
  ThrowingTNT: 5000
  PlayerLauncher: 5000
  Webber: 5000
  RodOfInvisibility: 5000
  Boost: 5000
  Chikun: 5000
  Steal: 5000

# Points make up the cuboid where players can break blocks
# Being outside this cuboid will leave players from the arena
ArenaArea:
  One:
    x: 0
    y: 0
    z: 0
  Two:
    x: 0
    y: 0
    z: 0

# Points make up the cuboid where players will wait or watch
# Being outside this cuboid will leave players from the waiting/watching list
WaitArea:
  One:
    x: 0
    y: 0
    z: 0
  Two:
    x: 0
    y: 0
    z: 0

# Commands run by the player before entering the arena
PrestartCommands:
  - v off

# Commands that can be run by players inside the arena
# These should only be the first word of the command
# Ex: "/pm Notch" should not be in this list
# Ex: "/pm" can be in this list
WhitelistCommands:
  - /floor
  - /m
  - /t

# How often to check the arena (number of ingame ticks)
TicksPerCheck: 5

# Start degrading after 'x' FloorIsLava tick
StartDegradeOn: 25

# Degrade every 'x' FloorIsLava ticks once degrading is started
DegradeOnTick: 15
